import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({ ok: true, app: 'gas-india' }));
app.get('/', (req, res) => res.send('gas-india API running. See README for roadmap.'));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`gas-india on ${port}`));
